services:
  backend:
    build:
      context: ./backend
    container_name: go_backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:leandra@db:5432/notessharing?sslmode=disable
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: leandra
      POSTGRES_DB: notessharing
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend

volumes:
  db_data: